### ISSUE TITLE
SourceMgr could provide a way to find the latest revision on a branch

### ISSUE THREAD

**Issue by adg** [sdboyer/gps#117]
The situation:

We have a manifest file that specifies a branch constraint.
the lock specifies the specific revision.
We'd like the `dep status` command to display the most recent revision on that branch, if it is different from the one in the lock file.

The `SourceMgr` has a method `ListVersions`, which does contain the branch itself, but doesn't tell us anything about it. 

Could there be another method, like this?
```
LatestRevision(id ProjectIdentifier, branch gps.Version) gps.Version
```
Does that make sense?

**Comment by sdboyer** [comment]
`ListVersions()` should return what you need, I think. Try asserting the returned value representing the branch to `gps.PairedVersion`, then calling `Underlying()` on it. So...

```go

var r gps.Revision
vlist, _ := sm.ListVersions(id)
for _, v := range vlist {
    if tv, ok := v.(gps.PairedVersion); ok && v.Type() == "branch" {
        r = tv.Underlying()
        break
    }
}
```

**Comment by sdboyer** [comment]
While it's not a type-level guarantee that all the versions returned from `ListVersions()` will be `PairedVersion` (mostly for forwards compatibility reasons - i anticipate there may be source types in the future that don't do it, and don't want to force it on them), I think that all of the existing implementations will always return `PairedVersion`s.

**Comment by sdboyer** [comment]
If it's easier, though, I don't think I have any objections to adding such a method. It'd probably be `LatestVersion()`, though, and return a `Version` that is probably type-assertable to `PairedVersion`.

**Comment by adg** [comment]
Given that this works fine, I think we can close this feature request.
