### ISSUE TITLE
Separate ListPackages, PackageTree into subpackage

### ISSUE THREAD

**Issue by sdboyer** [sdboyer/gps#166]
The primary `gps` package is becoming somewhat unwieldy, so it's worth starting to separate out logic dealing with discrete subsystems into their own subpackages. Unfortunately, a lot of gps' systems are deeply interwoven, so this isn't easy to do in a lot of areas.

One exception, though, is the family of functions around `PackageTree` - they're quite well self-contained. They're also growing, and are likely to continue to grow as we refine that subsystem. So, they're a good first candidate for separation into a subpackage.

**Comment by sdboyer** [comment]
Oh, this is all done. Thanks, @narqo!

**Comment by narqo** [comment]
(☞ﾟヮﾟ)☞
