### ISSUE TITLE
Check pkgs len when removing from unselected queue

### ISSUE THREAD

**Issue by sdboyer** [sdboyer/gps#174]
golang/dep#274 demonstrated a bug in the unselected queue, where when attempting to remove a bmi with the same ident but a longer-length list of packages, we could overrun the slice in the queue and cause a panic.

**Comment by zbintliff** [comment]
sdboyer not sure if you were going to tackle this because its breaking things currently. If not i'd like to try to help. Been trying to find a way to contribute to the `dep` project.

**Comment by sdboyer** [comment]
@zbintliff i'm actually fixing it right now :/ the enthusiasm to get involved is awesome, though! 

i'll roll a 0.14.1 once it's fixed - maybe you can take care of putting up a PR to merge the gps update into dep? i know it's a small thing, but i'm working on getting the roadmap up for all of dep atm though, so there should be more things to tackle soon 😄

**Comment by zbintliff** [comment]
@sdboyer figured. Will do and thanks

**Comment by sdboyer** [comment]
OK, v0.14.1 is up - fire away with a PR against dep!
