### ISSUE TITLE
Convert table-based tests to subtests

### ISSUE THREAD

**Issue by sdboyer** [sdboyer/gps#175]
Go 1.7 introduced [subtests](https://blog.golang.org/subtests), which are great. We should convert our (simple, non-mutating) table-based tests to use them. That includes:

* `TestWorkmapToReach`
* `TestListPackages`
* `TestDeduceFromPath`
* `TestVanityDeduction`
* `TestIsStdlib`
* `TestLockedProjectsEq`
* `TestGetApplicableConstraints`
* `TestBasicSolves`
* `TestBimodalSolves`

These definitely could use conversion. Others arguably could/should be converted, too. And, I may have missed some.

**Comment by zbintliff** [comment]
I'll take a look at this.  Writing tests is the easiest way for me to grok a project.  I'm also travelling a bunch the next few weeks so it might take some time.

**Comment by zbintliff** [comment]
Would you be opposed to pulling in [testify](https://github.com/stretchr/testify) for spec like tests?

**Comment by sdboyer** [comment]
@zbintliff awesome! i'm the same way - ain't nothing like writing tests to get my head around something.

I'd rather not pull in testify. Any deps we use are likely to have to make it into the toolchain in some form, so we need to keep to the barest of essentials. Being that this issue, at least, is a more straightforward conversion of table-based tests to use subtests, it shouldn't really matter, anyway.

**Comment by zbintliff** [comment]
Ah that's completely valid. I've just grown accustomed to spec asserts.

OK I'll say I'll take the first two listed above leaving it open. For
others to contribute. If I get the groove of things (more importantly the
time) I'll take a few more cases.

**Comment by zbintliff** [comment]
So converting the tests are pretty trivial.  I started the first one and wanted to make sure you were cool with everything before I knocked a bunch out.

**Comment by zbintliff** [comment]
Ok, risking the PR getting to bloated (not sure how you want to break it up). #178 contains the first four functions.

**Comment by sdboyer** [comment]
I'm fine with just doing them all in one place. It's a lot of lines changed, but still conceptually simple what's going on; I see no particular reason to break it up over multiple PRs.

**Comment by zbintliff** [comment]
PR is update for all mentioned functions except `TestIsStdlib`. Can't find that one:
```
$ ag TestIsStdlib
$
```

**Comment by sdboyer** [comment]
yeah, i constructed that list by hand...must've messed that one up somehow. that does suggest i might have missed a test or two, though - do you mind doing a quick check through the existing tests to see if they look table-y?

**Comment by zbintliff** [comment]
I think this can be closed now?

**Comment by sdboyer** [comment]
ah yes, thanks!
