### ISSUE TITLE
Traverse into symlinked dirs in ListPackages

### ISSUE THREAD

**Issue by sdboyer** [sdboyer/gps#177]
Follow up to #157 - we need a custom reimplementation of `filepath.Walk()` that lets us not just superficially visit, but actually traverse down into relatively-symlinked directories within `ListPackages()`.

...or, at least, we need to have the returned `PackageTree` make it seem like that's what we did. When we encounter an internal symlink, it should be perfectly possible to only scan the underlying referent, then copy over the results into the corresponding symlinked paths after parsing is done. That is, if we have this dir structure:

```
foo
foo/bar
baz -> foo
```

Then we should only need to parse `foo` and `foo/bar`, and can then know to copy `foo` to `baz` and `foo/bar` to `baz/bar`.

**Comment by sdboyer** [comment]
So, I started working on the implementation, and found myself down in the weeds of repeat calls to heuristically check for symlink cycles (a la `filepath.EvalSymlinks()`) within the lexically-bounded path subtree that contains the project. If you look at the implementation there, you'll see that it doesn't even really do loop detection - it just walks links until it hits a limit (255), then quits. [Apparently this is fairly normal](http://unix.stackexchange.com/questions/99159/is-there-an-algorithm-to-decide-if-a-symlink-loops).

At this point, the code is _really_ starting to smell, and for a really minimal amount of value. The original example from #157 - https://github.com/douban/libmc - has an internal symlink, but _all_ that does is make it possible to access those packages from two different paths within the repository. That's actually NOT a good thing. Not only does it potentially duplicate package initializers and create ambiguity about what the packages' actual names are...but it added literally nothing, because it was perfectly possible to import through the `src` path; `golibmc` is superfluous.

So, I have to close this, and unfortunately, revert #157. Sorry to put you through all that @ReSTARTR :(

**Comment by ReSTARTR** [comment]
O...Okay... This is sad news for me;-(
But, as you say, [the issue that I mentioned before](https://github.com/sdboyer/gps/pull/157#issuecomment-275318479) will be resolved with importing from `src` .
You know, it is difficult to correctly treat symlinks :cry:
Thank you anyway!
