### ISSUE TITLE
TestGetSources asks for user input, so it hangs indefinitely

### ISSUE THREAD

**Issue by spenczar** [sdboyer/gps#184]
`manager_test.go`'s `TestGetSources` hangs indefinitely for me, saying this:

```
=== RUN   TestGetSources
The authenticity of host 'bitbucket.org (104.192.143.2)' can't be established.
RSA key fingerprint is SHA256:zzXQOXSRBEiUtuE8AikJYKwbHaxvSc0ojez9YXaGp1A.
Are you sure you want to continue connecting (yes/no)?
no
no pls
pls exit :(
```

The last three lines are mine :)

**Comment by spenczar** [comment]
I only get this error if I don't have mercurial installed. Maybe we should just skip or fail the test with a clear message in that case?

**Comment by sdboyer** [comment]
Wow, that's super weird. But yes, let's fail the test if `hg` isn't installed, with a message indicating as much.
