### ISSUE TITLE
gps capable of managing more than just go packages?

### ISSUE THREAD

**Issue by jlgerber** [sdboyer/gps#220]
How generic is gps with respect to the packages themselves? Is this designed to be applied to package management in a general? I am toying with the idea of rewriting an internal package management system we have at work in Go; this potentially provides a couple of key components ( sat solver, semver api ), but the packages in question are comprised of plug-ins, libraries, and executables in a variety of languages. ( something like https://github.com/nerdvegas/rez ).

**Comment by sdboyer** [comment]
Hi! Unfortunately, gps is very tightly bound to the Go case; it relies on a number of assumptions specific to Go's system of naming packages, as well as static analysis of actual Go code. 😢 

I've toyed with the idea of writing a more generic package management library, but...well, that's a project for when all this is wrapped up 😄
