### ISSUE TITLE
Undo (godep) import rewriting on the fly in listPackages

### ISSUE THREAD

**Issue by sdboyer** [sdboyer/gps#79]
For import path analysis to be correct, `listPackages` needs to determine if an import path has been rewritten and, if so, rewrite it back into its standard form. Without this, we'll mistake old-school godep-rewritten import paths as being internal packages.

This is not a harmless problem. I'm not actually sure just what the effects would be offhand, but either:
- there would be panics/errors due to trying to import an internal package that "doesn't exist," because we don't walk into `Godeps` dirs with `listPackages()`. (this is kinda the preferred outcome, actually)
- all of the external deps of all of the transitive deps that godep pulled in would be treated as external deps of the project itself. none of them would be treated as individual projects with the appropriate autonomy to move and have versions in the graph. It'd all get lumped together. This would basically be armageddon for the solver.

either way, this needs to be addressed.

**Comment by sdboyer** [comment]
#94 has the fix at the `listPackages()` level, but that's not sufficient. It works fine for while the solver is running, but the import statements need to _actually_ get rewritten after they've made it out into a vendor directory. There's basically just two ways of doing that:

1. ALWAYS scan ALL packages to see if they need to have their imports rewritten, after having written them out to `vendor/` (or wherever).
2. Include something in lock data indicating to a tool that it's necessary for rewriting to take place.

As the caps...uh, suggest, I think the first approach is a terrible idea. Not only is it a nontrivial performance hit, but it means we're silently sliding in a code transformation without it being visible to the user. The only advantage is that there's literally no case I can conceive of where it's correct to leave the import paths munged. Thus, requiring lock data to be there in order for rewriting to happen is an instance of relying on explicit config for information we could detect from source code analysis - which is generally against my design philosophy for gps.

That said, this is the lock data, not manifest - it's all generated anyway. If someone goes manually mucking about with what's in there, oh well. Plus, beyond the performance benefits, I think it's really quite preferable for the base operating mode to be always, only, and strictly dropping the unaltered code from a source directly on disk. Any transformations or modifications that are made should be explicitly listed.

**Comment by sdboyer** [comment]
After discussion on this during last night's pm committee meeting, I'm putting this on hold. Because:

* It necessarily adds a category of behavior to the lock file (transforms) that has complex interrelationships with other considerations
* godep hasn't rewritten import paths in a year, so they're increasingly a decrepit thing of the past and so maybe aren't even a prevalent enough case that we really have to deal with it
* ...and, a third thing that @adg was pointing out that I've now forgotten. Maybe he can summarize it here :)

**Comment by adg** [comment]
I don't remember either. :-/

**Comment by sdboyer** [comment]
no worries, not essential to have it here

**Comment by sdboyer** [comment]
Scratch this, we're just not doing it
