### ISSUE TITLE
Stop using go/build, implement our own from go/parser

### ISSUE THREAD

**Issue by sdboyer** [sdboyer/gps#99]
There are a few reasons why relying on `build.ImportDir()`, even with a carefully mangled `build.Context` object, doesn't do what we need. The single most important thing is that we need to take a combinatorial view of build tags, primarily os/arch. This gets potentially explode-y, but my current thinking is that we'd want a distinct logical "Package" for each combination of build tags that corresponds to a unique file set.

**Comment by freeformz** [comment]
I am playing with gps to better understand it, so I hacked in some support for [gps to godep](https://github.com/tools/godep/compare/gps) (in parallel with it's normal work), which saves the gps vendored bits to `vendor_gps`. This way I can `diff -ur vendor vendor_gps` and figure out what's different.

My hack uses a ./Godeps/Godeps.json file as lock data for the solver.

When it tries to solve the existing deps it works for everything except x/tools/go/vcs (locked to 1f1b3322f67af76803c942fd237291538ec68262), instead getting f8f91591b720f65816369d36e577b525d0926902, which is very old.

Turning on trace I see this...

```console
| | | ✓ select github.com/kr/fs@2788f0dbd16903de03cb8186e5c7d97b69ad387b w/1 pkgs
| | | | ? attempt golang.org/x/tools with 1 pkgs; at least 1 versions to try
| | | | | try golang.org/x/tools@1f1b3322f67af76803c942fd237291538ec68262
| | | | ✗ /Users/emuller/.godep/cache/sources/https---go.googlesource.com-tools/cmd/fiximports/testdata/src/old.com/bad/bad.go:2:43: expected 'package', found 'EOF'
| | | | | try golang.org/x/tools@master
| | | | ✗ /Users/emuller/.godep/cache/sources/https---go.googlesource.com-tools/cmd/fiximports/testdata/src/old.com/bad/bad.go:2:43: expected 'package', found 'EOF'
| | | | | try golang.org/x/tools@release-branch.go1.2
```

FWIW: stuff like this is why godep stopped using build.Context for parsing stuff and I ended up having to write my own [parser](https://github.com/tools/godep/blob/master/list.go).

**Comment by sdboyer** [comment]
That commit should fix the EOF issue, containing the damage to just the problem package.

**Comment by sdboyer** [comment]
While there's still work to do here, we've accomplished the basic goal - no more reliance on `build.ImportDir`.
